### ISSUE TITLE
Request a simple option

### ISSUE THREAD

**Issue by nxrighthere** [rubyu/CreviceApp#3]
Thank you for the great application! This is exactly what I've been looking for the last few days. Only one option that I really miss is a possibility to not show the application icon in the system tray. I would like to set Crevice to stay only in background processes.

**Comment by rubyu** [comment]
What use case would you think? The icon in the tasktray is the only one thing which provides way to access the Crevice's main window. If it does not exist, user should manage Crevice by himself properly. Would you need to execute Crevice as a CUI tool, a windows service, or other way? I think the implementation will easily be made just adding CUI interface and omitting codes relating GUI.

**Comment by nxrighthere** [comment]
CUI would be good.

**Comment by rubyu** [comment]
I understood. I will implement CUI interface including the flag which prevent to show the taskbar icon.

**Comment by rubyu** [comment]
I released Crevice 3.1.175 (https://github.com/rubyu/CreviceApp/releases/tag/3.1) added command line interface including --nogui option now. Please try it. 

Note: I had fixed typo `baloon` in API names by this version, so if you are using it, please fix it.

**Comment by nxrighthere** [comment]
I tried to launch the app with this option and for some reason it's not starting, but it works fine without --nogui.

**Comment by nxrighthere** [comment]
It appears in the system tray for a second, and then just closes without any notification.

**Comment by rubyu** [comment]
Sorry, give a try https://github.com/rubyu/CreviceApp/releases/tag/3.2

**Comment by nxrighthere** [comment]
Thank you! Now it works fine! 🎉

**Comment by rubyu** [comment]
In command prompt, the command following still a bit buggy:
```
> CreviceApp.exe --nogui
```
After launching application, control should return to command prompt, but Crevice of this version require one Enter press to return to the command prompt. This seems common bug of dotnet Form application.  
See [Console Output from a WinForms Application : C\# 411](http://www.csharp411.com/console-output-from-winforms-application/).

I found compiling as console application may solve this problem. So I will try this later.

**Comment by nxrighthere** [comment]
I launch Crevice from a shortcut, so for me it's not a problem. 👌

**Comment by rubyu** [comment]
In addition, assembly caching feature introduced by 3.0 is enabled by default and does not tested well yet. If anything odd things occurred relating user script, please use --nocache option to avoid the problem and tell me that.

**Comment by nxrighthere** [comment]
Sure, at the moment I noticed that the application is starting much faster than before, and I really like it.
