### ISSUE TITLE
App logo/icon

### ISSUE THREAD

**Issue by nxrighthere** [rubyu/CreviceApp#4]
I made a logo/icon for your lovely application. If you like it, feel free to use it.

Logo

![Logo](https://i.imgur.com/oFi2VKc.png)

Icon

![Icon](https://i.imgur.com/E4F18zB.png)

Example

![Example](https://i.imgur.com/1FgVZZq.png)

[Download](https://ufile.io/kigkx)

**Comment by rubyu** [comment]
Thanks!!!  I'm very glad to your contribution! Very Cool 😂
